### PR TITLE
fixed LDUR pretty printing bug

### PR DESCRIPTION
**Pull request by lukeg101**
This patch removes an erroneous `#` which is printed it shouldn't be.

### CODE REVIEW

**Comment by lukeg101** [comment]
Hi @relokin, I found this PR from last year affects upstream, would you mind having  a look at this patch as well?

**Review by relokin — COMMENTED** [review]
I am sure I understand the problem. AArch64 assembly uses `#` in front of immediate operands https://developer.arm.com/documentation/dui0801/g/A64-Data-Transfer-Instructions/LDUR

If I understand correctly and the current code means that we print the instruction like 
```
LDUR X0,[X1, #4]
```
then I think there is nothing wrong. If I misunderstood and we print # twice then we should remove it. I think there are more cases like this.

**Comment by lukeg101** [comment]
Hi Nikos, 
It is the latter case - we print two `##`. This is because `m.pp_k` prints a `#` in front of the literal, and the `sprintf` call also prints a `#`. I haven't observed this with other types (yet - I did look)

**Comment by relokin** [comment]
I see. Thanks! Feel free to post upstream but you might want to fix `I_LDUR_SIMD` and `I_STUR_SIMD` too while you're at it.

**Comment by lukeg101** [comment]
sorry something has gone wrong with this push - it included a lot of old commits, I will fix and try again

**Pull request closed without merging**
